name: Trigger Prerelease
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: yarn install --frozen-lockfile
      - run: yarn run-script trigger-prerelease
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
