name: Release
on:
  push:
    branches:
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn run-script prepare-insiders-build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn build
